# Generated by Django 5.2.14 on 2026-06-02 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('role', models.CharField(choices=[('worker', 'Compute Worker'), ('head', 'Cluster Head'), ('storage', 'SE Storage Element')], default='worker', max_length=50)),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Degraded', 'Degraded'), ('Recovering', 'Recovering'), ('Dead', 'Dead')], default='Healthy', max_length=50)),
                ('thread_count', models.IntegerField(default=4)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='SpaceWeatherWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geomagnetic_kp_index', models.FloatField(default=3.0, help_text='Simulated or real geomagnetic index (0-9)')),
                ('solar_wind_speed', models.FloatField(default=400.0, help_text='Solar wind speed in km/s')),
                ('stress_multiplier', models.FloatField(default=1.0, help_text='Computed stress scale factor for cluster load generation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(help_text='CPU utilization percentage')),
                ('ram_usage', models.FloatField(help_text='RAM utilization percentage')),
                ('network_rx', models.FloatField(help_text='Network download speed in MB/s')),
                ('network_tx', models.FloatField(help_text='Network upload speed in MB/s')),
                ('active_jobs', models.IntegerField(default=0, help_text='Number of running grid job tasks')),
                ('is_anomaly', models.BooleanField(default=False, help_text='Flagged by ML Anomaly Detection engine')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='nodes.gridnode')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['node', '-timestamp'], name='nodes_telem_node_id_5fda81_idx')],
            },
        ),
    ]
