# Generated by Django 5.2.14 on 2026-06-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_systemevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceweatherworkload',
            name='is_live',
            field=models.BooleanField(default=True, help_text='Indicates if the metrics are pulled from NASA API vs simulated local cycle'),
        ),
    ]
