# Generated by Django 5.2.14 on 2026-06-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_spaceweatherworkload_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceweatherworkload',
            name='base_kp_index',
            field=models.FloatField(default=3.0, help_text='Raw baseline geomagnetic index'),
        ),
        migrations.AddField(
            model_name='spaceweatherworkload',
            name='base_solar_wind_speed',
            field=models.FloatField(default=400.0, help_text='Raw baseline solar wind speed'),
        ),
    ]
