# Generated by Django 5.2.14 on 2026-06-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_spaceweatherworkload_base_kp_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrymetric',
            name='stress_multiplier',
            field=models.FloatField(default=1.0, help_text='Workload stress multiplier when this metric was recorded'),
        ),
    ]
